---
before_install:
  - rm .travis.yml
  - sudo apt-get install -qq postgresql-9.1 build-essential libgeos-dev flex autoconf libtool gdb gfortran postgresql-plpython-9.1 postgresql-server-dev-all python-psycopg2 xsltproc libproj-dev python2.7-dev dblatex 
  - git config --global user.name "PostGIS TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - wget -q http://download.osgeo.org/geos/geos-3.4.1.tar.bz2
  - tar xvjf geos-3.4.1.tar.bz2
  - whoami
  - sudo -l -u postgres createuser -s postgis
install:
  - ./autogen.sh
  - ./configure
language: c
script:
  - ./make
  - ./make check
