---
env:
  global:
    - POSTGRES_VERSION=9.1.0
    - GEOS_VERSION=3.4.1
    - GDAL_VERSION=1.9.2
before_install:
  - rm .travis.yml
  - git config --global user.name "PostGIS Travis CI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
language: c
compiler:
  - gcc
script:
  - ./travis_install.sh
after_failure:
  - cat /tmp/pgis_reg/*
