---
env:
  global:
    - POSTGRES_VERSION=9.1
  matrix:
    - GEOS_VERSION=3.4.1 GDAL_VERSION=1.9.2
before_install:
  - rm .travis.yml
  - git config --global user.name "PostGIS Travis CI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - ./travis_install.sh
language: c
compiler:
  - gcc
script:
  - make
  - make check RUNTESTFLAGS=-v
after_failure:
  - cat /tmp/travis.*
  - cat /tmp/pgis_reg/*
