---
env:
  global:
    - GDAL_VERSION=1.9.2
    - PGUSER=postgres
  matrix:
    - GEOS_VERSION=3.4.1
    - GEOS_VERSION=3.3.8
before_install:
  - rm .travis.yml
  - sudo apt-get update
  - sudo apt-get install -qq build-essential flex autoconf libtool gfortran postgresql-server-dev-all xsltproc libproj-dev dblatex xsltproc libcunit1-dev libcunit1
  - git config --global user.name "PostGIS TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - export LSB_RELEASE=$( lsb_release -rs )
  - wget -q http://stardestroyer.de/travis/geos-$GEOS_VERSION.travis.$LSB_RELEASE.tar.gz
  - tar xvzf geos-$GEOS_VERSION.travis.$LSB_RELEASE.tar.gz -C / 
  - sudo ln -s /home/travis/geos-$GEOS_VERSION/lib/libgeos_c.so.1.8.0 /usr/lib/libgeos_c.so.1
  - wget -q http://stardestroyer.de/travis/gdal-$GDAL_VERSION.travis.$LSB_RELEASE.tar.gz
  - tar xvzf gdal-$GDAL_VERSION.travis.$LSB_RELEASE.tar.gz -C / 
  - ./autogen.sh
  - ./configure --with-geosconfig=/home/travis/geos-$GEOS_VERSION/bin/geos-config --with-gdalconfig=/home/travis/gdal-$GDAL_VERSION/bin/gdal-config
language: c
script:
  - make
  - make check
after_failure:
  - cat /tmp/pgis_reg/*
