---
env:
  global:
    - GDAL_VERSION=1.9.2
  matrix:
    - GEOS_VERSION=3.4.1
    - GEOS_VERSION=3.3.8
before_install:
  - rm .travis.yml
  - sudo apt-get update
  - sudo apt-get install -qq postgresql-9.1 build-essential flex autoconf libtool gfortran postgresql-server-dev-all xsltproc libproj-dev dblatex libgdal-dev xsltproc
  - git config --global user.name "PostGIS TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - sudo -l -u postgres createuser -s travis
install:
  - export LSB_RELEASE=$( lsb_release -rs )
  - wget -q http://stardestroyer.de/travis/geos-$GEOS_VERSION.travis.$LSB_RELEASE.tar.gz
  - tar xvjf geos-$GEOS_VERSION.travis.$LSB_RELEASE.tar.gz -C / 
  - wget -q http://stardestroyer.de/travis/gdal-$GDAL_VERSION.travis.$LSB_RELEASE.tar.gz
  - tar xvjf gdal-$GDAL_VERSION.travis.$LSB_RELEASE.tar.gz -C / 
  - ./autogen.sh
  - ./configure --with-geosconfig=/home/travis/geos-${GEOS_VERSION}/bin/geos-config --with-gdalconfig=/home/travis/gdal-${GDAL_VERSION}/bin/gdal-config
language: c
script:
  - ./make
  - ./make check
